---
on:
  pull_request: &ignore-paths
    paths-ignore:
      - ".gitattributes"
      - ".gitignore"
      - "CHANGELOG.md"
      - "docs/**"
      - "README.md"

  push: *ignore-paths

name: Composer require checker

jobs:
  composer-require-checker:
    uses: yii2-framework/actions/.github/workflows/composer-require-checker.yml@main
