---
on:
  pull_request: &ignore-paths
    paths-ignore:
      - ".gitattributes"
      - ".gitignore"
      - "CHANGELOG.md"
      - "docs/**"
      - "README.md"

  push: *ignore-paths
name: ecs

jobs:
  easy-coding-standard:
    uses: yii2-framework/actions/.github/workflows/ecs.yml@main
