---
on:
  pull_request: &ignore-paths
    paths-ignore:
      - ".gitattributes"
      - ".gitignore"
      - "CHANGELOG.md"
      - "docs/**"
      - "README.md"

  push: *ignore-paths

name: static analysis

jobs:
  phpstan:
    uses: yii2-framework/actions/.github/workflows/phpstan.yml@main
